Parse for statements
moshell-lang/moshell pull request #59
Opened 2023-03-12 11:32 UTC by syldium

There are two kinds of `for` statements. The initializer/condition/increment `for`:

```bash
for ((val i = 0; $i < 10; i=$(( $i + 1 )))) {
  echo $i
}
```

And the `for` in range loop:
```bash
for n in 1..5; echo $n
for i in (1 + 1)..5; echo $i
for j in $a..$b; echo $j
for arg in $@ {
  echo $arg
}
```

This PR introduces the notion of iterable, which can be a reference to a variable, a file pattern or an int iterator.

Here's an example of a valid file pattern:
```bash
for file in * {
  if test -f $file {
    echo $file
  }
}
```

The parser also provides some interesting parse errors:

```
  × Expected variable name before 'in'
   ╭─[stdin:1:1]
 1 │ for in 0..10; echo $i
   ·     ─┬
   ·      ╰── Here
   ╰────
```
```
  × Receiver variables do not start with '$'
   ╭─[stdin:1:1]
 1 │ for $arg in $@ {
   ·     ┬
   ·     ╰── Here
   ╰────
  help: Consider removing the '$' prefix: for arg in $@
```
And other messages...

Fix #29

2023-03-12 14:31 UTC, Override-6 commented on parser/src/aspects/loop.rs
> +            repeat_nm(2, 2, of_type(TokenType::RoundedLeftBracket)),
```suggestion
times(2, of_type(TokenType::RoundedLeftBracket)),
```

2023-03-12 14:33 UTC, Override-6 commented on parser/src/aspects/loop.rs
> +        }
why push the _same_ delimiter two times in the stack as a closing delimiter such as `)<x>)` is invalid.

2023-03-12 15:09 UTC, Override-6 requested changes

2023-03-12 15:09 UTC, Override-6 commented on parser/src/aspects/loop.rs
> +            );
We can't iterate on a predefined item collection :
```rs
for i in a b c d { .. }
// or : 
for i in Array(a b c d) { .. } 
```

2023-03-12 15:09 UTC, Override-6 commented on parser/src/aspects/loop.rs
> +            .advance(repeat_nm(2, 2, of_type(TokenType::Dot)))
```suggestion
            .advance(times(2, of_type(TokenType::Dot)))
```

2023-03-12 15:13 UTC, Override-6 commented
Very good work btw

2023-03-14 19:31 UTC, syldium commented
Now implement ranges as values and a subset of file patterns.

Fix #60

2023-03-15 19:52 UTC, Override-6 approved these changes

2023-03-15 20:04 UTC, merged